targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/ranking/models/rank.dart
            - lib/reset/reset_date.dart
            - lib/calendar/memo/models/memo.dart
      json_serializable:
        generate_for:
          include:
            - lib/ranking/models/rank.dart
            - lib/reset/reset_date.dart
            - lib/calendar/memo/models/memo.dart
        options:
          any_map: true
          explicit_to_json: true